spring:
  application:
    name: loadflow-server


  cloud:
    function:
      definition: consumeRun;consumeCancel
    stream:
      bindings:
        consumeRun-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.run
          group: loadflowGroup
          consumer:
            concurrency: 4
        publishRun-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.run
        publishResult-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.result
        consumeCancel-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.cancel
        publishCancel-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.cancel
        publishStopped-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.stopped
        publishFailed-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.failed
      output-bindings: publishRun-out-0;publishResult-out-0;publishCancel-out-0;publishStopped-out-0;publishFailed-out-0

powsybl-ws:
  database:
    name: loadflow

# default values for loadflow providers "Hades2" or "OpenLoadFlow"
loadflow:
  default-provider: OpenLoadFlow
