spring:
  application:
    name: loadflow-server

  cloud:
    function:
      definition: consumeRun;consumeCancel
    stream:
      bindings:
        consumeRun-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.run
          group: loadflowGroup
          consumer:
            concurrency: 4
            max-attempts: 1
        publishRun-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.run
        publishResult-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.result
        consumeCancel-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.cancel
        publishCancel-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.cancel
        publishStopped-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.stopped
        publishCancelFailed-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.cancelfailed
      output-bindings: publishRun-out-0;publishResult-out-0;publishCancel-out-0;publishStopped-out-0;publishFailed-out-0;publishCancelFailed-out-0
      rabbit:
        bindings:
          consumeRun-in-0:
            consumer:
              auto-bind-dlq: true
              dead-letter-exchange: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.run.dlx
              dead-letter-routing-key:
              dead-letter-queue-name: ${powsybl-ws.rabbitmq.destination.prefix:}loadflow.run.dlq
              quorum:
                enabled: true
                delivery-limit: 2
powsybl-ws:
  database:
    name: loadflow

# default values for loadflow providers "DynaFlow" or "OpenLoadFlow"
loadflow:
  default-provider: OpenLoadFlow
  default-limit-reductions:
    providers: [OpenLoadFlow]
    voltageLevels:
      - nominalV: 20
        lowBound: 5
        highBound: 30
      - nominalV: 45
        lowBound: 30
        highBound: 55
      - nominalV: 63
        lowBound: 55
        highBound: 75
      - nominalV: 90
        lowBound: 75
        highBound: 120
      - nominalV: 150
        lowBound: 120
        highBound: 180
      - nominalV: 225
        lowBound: 180
        highBound: 300
      - nominalV: 400
        lowBound: 300
        highBound: 500
    limitDurations:
      - lowBound: 600
        lowClosed: false
        highBound: ~
        highClosed: false
      - lowBound: 300
        lowClosed: true
        highBound: 600
        highClosed: true
      - lowBound: 0
        lowClosed: true
        highBound: 300
        highClosed: false
    defaultValues:
      - [ 1, 1, 1, 1 ]
      - [ 1, 1, 1, 1 ]
      - [ 1, 1, 1, 1 ]
      - [ 1, 1, 1, 1 ]
      - [ 1, 1, 1, 1 ]
      - [ 1, 1, 1, 1 ]
      - [ 1, 1, 1, 1 ]
