server:
  port: 5008

spring:
  rabbitmq:
    addresses: localhost

powsybl-ws:
  database:
    host: localhost

powsybl:
  services:
    network-store-server:
      base-uri: http://localhost:8080

gridsuite:
  services:
    report-server:
      base-uri: http://localhost:5028

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: prometheus, health, info

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
